# Generated by Django 4.2.5 on 2023-09-12 22:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_alter_writer_country'),
    ]

    operations = [
        migrations.RenameField(
            model_name='writer',
            old_name='birthYear',
            new_name='birth_year',
        ),
        migrations.RenameField(
            model_name='writer',
            old_name='deathYear',
            new_name='death_year',
        ),
    ]
