# Generated by Django 4.2.5 on 2023-09-12 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_rename_birthyear_writer_birth_year_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='writer',
            name='fav_quote',
            field=models.TextField(default='no', max_length=250),
            preserve_default=False,
        ),
    ]
