# Generated by Django 4.2.5 on 2023-09-13 22:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_writer_fav_quote'),
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.DateField()),
                ('type', models.CharField(choices=[('N', 'Novel'), ('S', 'Short stories collection'), ('P', 'Poetry collection')], default='N', max_length=1)),
                ('title', models.CharField(max_length=100)),
                ('writer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.writer')),
            ],
        ),
    ]
