# Generated by Django 4.2.5 on 2023-09-13 22:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_books'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Books',
            new_name='Book',
        ),
    ]
